
package com.mycompany.laberinto.view;

import com.mycompany.laberinto.controller.ControladorLaberinto;
import com.mycompany.laberinto.controller.ControladorPrincipal;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;


public class PanelLaberinto extends javax.swing.JPanel {

    private ControladorPrincipal controlador;
    private ControladorLaberinto controladorLaberinto;
    private ImageIcon laberintoGrafico;
    
    

    public PanelLaberinto(ControladorPrincipal controlador, GUIPrincipal guiPrincipal, ControladorLaberinto controladorLaberinto) {
        initComponents();
        this.controladorLaberinto = controladorLaberinto;
        this.controlador = controlador;
        laberintoGrafico = new ImageIcon("./src/main/resources/images/laberinto01.png");
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        laberintoGrafico.paintIcon(null, g, 0, 0);
        controladorLaberinto.getPersonaje().dibujar(g);
        controladorLaberinto.getEnemigo().dibujar(g);
        
        if (controlador != null) {
            controlador.dibujar(g);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTemp = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTemp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTemp.setText("jLabel1");
        lblTemp.setDisplayedMnemonicIndex(2);
        add(lblTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 120, 80));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTemp;
    // End of variables declaration//GEN-END:variables
}
